function DeployPaths
% DeployPaths shows the paths a compiled M-file sees at runtime, to
% compare them across operating systems. See CompileDeployPaths.
%
% Description:
%   For the plain .m, and for the compiled EXE on PCWIN, paths point
%   where expected (pwd is the EXE's own location). On Mac, launching
%   the .app bundle from Finder makes pwd/system('pwd') point to "/"
%   instead. Two workarounds: (1) set an env var (e.g. MANOSID), read it
%   via system('echo $MANOSID') and cd into it; (2) use the .sh launcher
%   generated by the Mac compiler, pointing it at the MATLAB/MCR install
%   (see the readme.txt generated alongside the build), e.g.
%   "./run_DeployPaths.sh /Applications/MATLAB_R2013a.app" - on a machine
%   without MATLAB, point it at the installed MCR instead.


str=sprintf('PLATFORM INDEPENDENT\n\npwd: %s\n\nctfroot: %s\n\nmfilename: %s\n\ncd: %s', pwd, ctfroot, mfilename('fullpath'), cd);
msgbox(str);

C=computer();
switch C
    case {'PCWIN', 'PCWIN64'}
        
    case 'MACI64'                
        [s, p]=system('pwd');
        [s, h]=system('echo $HOME');        
        strMAC=sprintf('MAC\n\npwd: %s\n\n HOME: %s\n\n',p, h);
        msgbox(strMAC);        
    otherwise
        error('computer-architecture not supported');
end
%f=uigetfile();
M = importdata('myfile.txt', ' ', 1);
 for k = [3, 5]
     disp(M.colheaders{1, k})
     disp(M.data(:, k))
     disp(' ')
 end

end