classdef imaqCam < handle & OM4MClassLib.DataStructs.IProps
    % imaqCam wraps a MATLAB Image Acquisition Toolbox camera (videoinput
    % object, configured via imaqtool), adding preview callbacks,
    % geometric calibration/undistortion, and HDR capture support
    %  Known gap: the constructor and Init() require a camGeomCal class
    % (this.gc) that does not exist anywhere in this repo, so
    % construction and geometric undistortion (Capture's geomCal option)
    % cannot currently work. Capture's HDR branch likewise calls
    % weight, makeImageMatrixFromIm, gsolve, hdrFromIm and reinhardGlobal,
    % none of which exist in src/ either (Debevec-style HDR helpers,
    % presumably from an external example not migrated from
    % om4mmatlabutils). Documented as-is, not fixed.
    
    
    %% propiedades
    
    %% protected props
    properties (Access=protected)
        props; % Camera propierties proetcted for potential inheritance
    end
    
    properties (Access=public) %GetAccess=private, SetAccess=private
        vid; %camera vid
        src; %vid sourcec.
        isStopped; %StopCam is executed
        sizeCData; %CData size of hImage (it does not must be the same than ImageSize that is linked with the acquisition device)
        FilterImagesFlag; %Filter data from acquired images to reduce noise
        FilterWindow; %Window size selected for filtering.
    end
    
    properties (Access=public) %GetAccess=public, SetAccess=public
        hImage; %handle of a image object is used for the preview function and the depicting of the results
        Data; %imaqCamData for hdr imaging
        gc; %geometric calibrator
    end
    
    %size of the captured image
    properties (Dependent=true, GetAccess=public, SetAccess=private)
        %ImageSize; %[NRows, NCols, NBands]
    end
    
    
    
    %% metodos publicos
    methods
        function this=imaqCam(vidIniFunc)
            % imaqCam constructs the camera from vidIniFunc, a handle to
            % a video object initialization function as generated by
            % imaqtool->File->Generate MATLAB code file; falls back to
            % getFirstImaqCamAvailable (with a warning dialog) if
            % vidIniFunc fails or returns an invalid videoinput
            import OM4MClassLib.Util.*
            callFunc=Logging.WhoCalledMe();
            
            try                
            %check input
            if not(isa(vidIniFunc, 'function_handle'))
                retMsg=[inputname(1) ' must be a function handle. The funcion must be created with imaqtool->file->Generate matlab code file'];
                error([callFunc, '->' retMsg]);
            end
            
            this.StopAllCameras();
            this.vid=vidIniFunc(); %load the vid object from the function handle vidIniFunc
            this.src=getselectedsource(this.vid);
            this.gc=camGeomCal();
            
            %check vid
            if not(isa(this.vid, 'videoinput')) || not(isvalid(this.vid))
                retMsg=[inputname(1) ' function does not initailice a valid video object'];
                error([callFunc, '->' retMsg]);
            end
            
            % Initialization
            this.Init();
            
            catch ME                
                this.vid=imaqCam.getFirstImaqCamAvailable;                
                this.src=getselectedsource(this.vid);
                this.gc=camGeomCal();
                
                % Initialization
                this.Init();
                retMsg=[ME.message, 'ERROR LOADING CAM: USING FIRST IMAQ CAM AVAILABLE'];
                opts = struct('WindowStyle','modal','Interpreter','tex');
                warndlg(retMsg, 'Warning', opts);
            end                                    
        end
        
        function srcInfo=getSrcInfo(this)
            % getSrcInfo returns propinfo(this.src) with each property's
            % current value added under srcInfo.(propName).Value
            %get props info
            srcInfo=propinfo(this.src);
            %get props vals
            srcPropNames = fieldnames(srcInfo) ;
            for n=1:length(srcPropNames)
                propName=srcPropNames{n};
                %add current value
                srcInfo.(propName).Value=this.src.(propName);
            end
            
        end
        
        function setSrcProp(this, propName, propVal)
            % setSrcProp sets this.src.(propName)=propVal, or warns if
            % propName is not a valid source property
            import OM4MClassLib.Util.*
            callFunc=Logging.WhoCalledMe();
            
            if isprop(this.src,propName)
                this.src.(propName) = propVal;
            else
                retMsg=[propName ': Invalid property'];
                warning([callFunc, '->' retMsg]);
            end
        end
        
        function propVal=getSrcProp(this, propName)
            % getSrcProp returns this.src.(propName), or NaN with a
            % warning if propName is not a valid source property
            import OM4MClassLib.Util.*
            callFunc=Logging.WhoCalledMe();
            
            if isprop(this.src,propName)
            propVal=this.src.(propName);
            else
                retMsg=[propName ': Invalid property'];
                warning([callFunc, '->' retMsg]);
                propVal=NaN;
            end
        end
        
        
        function delete(this)
            % delete stops and deletes this.vid when the imaqCam object
            % is destroyed
            if isa(this.vid, 'videoinput')
                stop(this.vid);
                delete(this.vid);
            end
        end
        
        function set.hImage(this, value)
            % set.hImage stores the preview image handle and caches its
            % CData size in this.sizeCData / the handle's appdata
            this.hImage=value;
            
            if ishandle(this.hImage)
                this.sizeCData=size(get(this.hImage, 'CData'));
                setappdata(this.hImage, 'sizeCData', this.sizeCData);
            end
        end
        
    end
    
    %% metodos publicos
    methods (Access=public)
        
        function Start(this)
            % Start begins acquisition (this.vid must use a manual
            % trigger) and initializes this.Data for a new capture
            import OM4MClassLib.Util.*
            callFunc=Logging.WhoCalledMe();
            %via software no es posible la sincronizacion si el trigger
            %esta a manual podemos mas o menos lanzarlo de forma sincrona
            %asumimos que la mayor parte del tiempo se va en la
            %inicializacion
            this.isStopped=false;
            
            if not(strcmp(this.vid.TriggerType, 'manual'))
                retMsg=['Invalid Trigger type trigger must be manual'];
                error([callFunc, '->' retMsg]);
            end
            
            if not(isrunning(this.vid))
                start(this.vid);
                %damos una pausa para dar tiempo a que las camaras se
                %inicializen OK
                pause(1);
                
            end
            
            %init data
            this.Data=imaqCamData;
            this.Data.VideoResolution=this.vid.VideoResolution;
            
        end
        
        function Capture(this, varargin)
            % Capture triggers this.vid and stores the result in
            % this.Data. Optional positional args (default false each):
            %  hdrImage: if true, sweeps exposures and computes an HDR
            %   radiance map/tonemap via weight/makeImageMatrixFromIm/
            %   gsolve/hdrFromIm/reinhardGlobal - NONE OF THESE FUNCTIONS
            %   EXIST IN src/, so hdrImage=true cannot currently run
            %  forceRadCal: if true (HDR only), recomputes and saves the
            %   per-channel response curves instead of loading them from
            %   this.props' hdrCalFile
            %  geomCal: if true, undistorts the result via this.gc
            %   (camGeomCal), which also does not exist in src/
            import OM4MClassLib.Util.*
            callFunc=Logging.WhoCalledMe();
            
            numvarargs = length(varargin);
            if numvarargs > 3
                retMsg=[callFunc ': requires at most 3 optional inputs the hdrImage, forceRadCal and geomCal'];
                error(retMsg);
            end
            
            % set defaults for optional inputs for [hdrImage, forceRadCal, geomCal]
            optargs = {false, false, false};
            
            % now put these defaults into the valuesToUse cell array,
            % and overwrite the ones specified in varargin.
            optargs(1:numvarargs) = varargin;
            % or ...
            % [optargs{1:numvarargs}] = varargin{:};
            
            % Place optional args in memorable variable names
            [hdrImage, forceRadCal, geomCal] = optargs{:};
            
            %las camaras tienen que estar running
            if not(isrunning(this.vid))
                retMsg=['Cameras must be running before ' callFunc];
                error([callFunc, '->' retMsg]);
            end
            
            if not(hdrImage)
                
                %primero lanzo el trigger y comienza la adquisicion
                %(el trigger esta a manual)
                trigger(this.vid);
                
                %espero a completar la adquisicion
                wait(this.vid, 10, 'logging');
                
                %getData
                [this.Data.I, ~, metadata] = getdata(this.vid, 1);
                
                if this.FilterImagesFlag == true
                    
                    for j = 1:size(this.Data.I,3) %Filter each image chanel 
                        
                        this.Data.I(:,:, j)=medfilt2(this.Data.I(:,:, j), this.FilterWindow);
                    
                    end
                    
                end
                
                this.Data.timeStamp=datestr(metadata.AbsTime,'mmm.dd,yyyy HH:MM:SS.FFF');
                
                if this.vid.FramesAvailable
                    stop(this.vid)
                    retMsg=[CallFunc ':LostFrame'];
                    warning(retMsg);
                end
                
                %undistort capture
                if geomCal
                    [this.Data.I, this.Data.X, this.Data.Y]=this.gc.undistortImage(double(this.Data.I));
                end
                
                
            else %hdrFlag==true
                propName='Exposure';
                srcInfo=this.getSrcInfo();
                
                expRange=srcInfo.(propName).ConstraintValue;
                
                
                maxExpVal=this.props.Get(char(imaqCamProps.maxExpVal)); % see Init to check default
                if expRange(2)< maxExpVal
                    maxExpVal = expRange(2);
                end
                
                expVals=maxExpVal:-1:expRange(1);
                exposureTimes=2.^double(expVals); %in s
                
                numExposures=length(expVals);
                tmax=1.5*exposureTimes(1); %in s
                imList=cell(1, numExposures);
                
                for n=1:numExposures
                    %set exp time
                    this.Stop();
                    this.setSrcProp(propName, expVals(n));
                    this.Start();
                    
                    %primero lanzo el trigger y comienza la adquisicion
                    %(el trigger esta a manual)
                    trigger(this.vid);
                    
                    %espero 2 exposuretimes a completar la adquisicion
                    wait(this.vid, tmax, 'logging');
                    
                    %getData
                    [I, ~, ~] = getdata(this.vid, 1);
                    [~,~,NP]=size(I);
                    %if GV convert to RGB
                    if NP==1
                        I=cat(3, I, I, I);
                    end
                    
                    if this.FilterImagesFlag == true
                    
                        for j = 1:size(I,3) %Filter each image chanel 
                        
                            I(:,:, j)=medfilt2(I(:,:, j), this.FilterWindow);
                    
                        end
                    
                    end
                
                    imList{n}=I;
                    
                    if this.vid.FramesAvailable
                        stop(this.vid)
                        retMsg=[CallFunc ':LostFrame'];
                        warning(retMsg);
                    end
                end
                
                % precompute the weighting function value
                % for each pixel
                weights = zeros(1, 255);
                for i=1:256
                    weights(i) = weight(i,1,256);
                end
                
                imSize=this.Data.VideoResolution;
                numPixels=imSize(1)*imSize(2);
                % load and sample the images
                [zRed, zGreen, zBlue, sampleIndices] = makeImageMatrixFromIm(imList, numPixels);
                
                B = zeros(size(zRed,1)*size(zRed,2), numExposures);
                
                %fprintf('Creating exposures matrix B\n')
                for i = 1:numExposures
                    B(:,i) = log(exposureTimes(i));
                end
                
                l=50; %lambda
                % solve the system for each color channel
                hdrCalFile=this.props.Get(char(imaqCamProps.hdrCalFile)); %see Init for default
                if forceRadCal
                    % fprintf('Solving for red channel\n')
                    [gRed,lERed]=gsolve(zRed, B, l, weights);
                    % fprintf('Solving for green channel\n')
                    [gGreen,lEGreen]=gsolve(zGreen, B, l, weights);
                    % fprintf('Solving for blue channel\n')
                    [gBlue,lEBlue]=gsolve(zBlue, B, l, weights);
                    save(hdrCalFile,'gRed', 'gGreen', 'gBlue');
                else
                    if exist(hdrCalFile, 'file') == 2
                        load(hdrCalFile);
                    else
                        retMsg=[callFunc ' HDR calibration file not found: ' hdrCalFile];
                        error(retMsg);
                    end
                end
                
                
                % compute the hdr radiance map
                %fprintf('Computing hdr image\n')
                
                hdrMap = hdrFromIm(imList, gRed, gGreen, gBlue, weights, B);
                %luminance
                L = 0.2125 * hdrMap(:,:,1) + 0.7154 * hdrMap(:,:,2) + 0.0721 * hdrMap(:,:,3);
                %tonemap
                
                % specify resulting brightness of the tonampped image. See reinhardGlobal.m
                % for details
                a = 0.72;
                % specify saturation of the resulting tonemapped image. See reinhardGlobal.m
                % for details
                saturation = 0.6;
                [ldrGlobal, ~ ] = reinhardGlobal( hdrMap, a, saturation );
                
                
                %save data to this.Data
                this.Data.I = hdrMap;
                this.Data.imList=imList;
                this.Data.L=L;
                this.Data.exposureTimes=exposureTimes;
                this.Data.toneMap=ldrGlobal;
                
                %undistort HDR specific
                if geomCal
                    [this.Data.L, ~, ~]=this.gc.undistortImage(this.Data.L);
                    [this.Data.toneMap, ~, ~]=this.gc.undistortImage(this.Data.toneMap);
                    [this.Data.I, this.Data.X, this.Data.Y]=this.gc.undistortImage(this.Data.I);
                else
                    [NR, NC, ~]=size(this.Data.I);
                    [this.Data.X, this.Data.Y]=meshgrid(1:NC, 1:NR);
                end
            end
            
            
            
            
            
        end
        
        
        
        
        function Stop(this)
            % Stop stops acquisition on this.vid
            stop(this.vid);
        end

        function SetUpdatePreviewWindowFcnCamera(this, hFcn)
            % SetUpdatePreviewWindowFcnCamera restarts the preview with
            % hFcn (a function handle taking (obj,event,hImage)) set as
            % this.hImage's UpdatePreviewWindowFcn, exposing this.props
            % to the callback via appdata
            this.StopPreview();
            %pass props to the hImage so callback functions can use them
            %without being connect to ythe imaqCam class
            setappdata(this.hImage,'camProps',this.props);
            setappdata(this.hImage,'UpdatePreviewWindowFcn',hFcn);
            this.StartPreview();
        end
        
        
        function StartPreview(this)
            % StartPreview starts the live preview into this.hImage
            preview(this.vid, this.hImage);
        end

        function StopPreview(this)
            % StopPreview stops the live preview
            stoppreview(this.vid);
        end


        function imSize = ImageSize(this)
            % ImageSize returns [NRows, NCols, NBands] for this.vid
            vidRes = get(this.vid, 'VideoResolution');
            nBands = get(this.vid, 'NumberOfBands');
            NR=vidRes(2);
            NC=vidRes(1);
            imSize=[NR, NC, nBands];
            
        end
        
    end
    
    %% metodos privados
    methods (Access=private)
        function this=Init(this)
            % Init configures this.vid for single-frame manual triggering,
            % creates a hidden preview figure/image handle, and sets
            % default props (corner-detection params, HDR exposure cap,
            % HDR calibration file name)


            %in R2015 the import (import OM4MClassLib.DataStructs.*;) does not work properly we must qualify the whole class name
            this.props=OM4MClassLib.DataStructs.PropsEnumList('imaqCamProps');
            
            %forzamos la configuracion del trigger a manual
            triggerconfig(this.vid, 'manual');
            
            %1 frame por triger y que paren cdo se llegue a los frames
            %indicados en TriggerRepeat
            set(this.vid, 'FramesPerTrigger', 1, 'TriggerRepeat', Inf);
            
            %aqui especificamos cada cuantas frames se ejectuta el evento FramesAcquired
            set(this.vid, 'FramesAcquiredFcnCount', 1);
            
            %this is usefull for some callbacks that have as input
            %parameter the vid object
            this.vid.UserData=this.vid;
            
            %init data
            this.Data=imaqCamData;
            this.Data.VideoResolution=this.vid.VideoResolution;
            
            %if the hImage are not init the setPreviewFcn does not
            %work
            %init hImages:
            ImSize=this.ImageSize;
            NR=ImSize(1); NC=ImSize(2);
            hFigure=figure('Toolbar','none',...
                'Menubar', 'none',...
                'NumberTitle','Off',...
                'Name','imaqCam Preview Window', 'Visible', 'off');
            
            %handle to RGB image
            this.hImage=imshow(cat(3,zeros(NR, NC), zeros(NR, NC), zeros(NR, NC)));
            
            %init isProcessing
            this.isStopped=false;
            
            %init filter values
            this.FilterImagesFlag=false;
            this.FilterWindow = [10 10];
            
            %init values for props
            detectCornerParams.QualityLevel=0.001;
            detectCornerParams.Method='Harris';
            detectCornerParams.SensitivityFactor=0.04;
            this.props.Set(char(imaqCamProps.detectCornerParams), detectCornerParams);
            this.props.Set(char(imaqCamProps.maxExpVal), 1); %1 sec
            this.props.Set(char(imaqCamProps.hdrCalFile), 'gMatrix.mat');
            
            %this prop must be set before use of the detect corners call
            %back see tests for more infor. Here basically changes the
            %screen resolution when used and makes necessary the prsence of
            %the computer vision toobox
            %this.props.Set(char(imaqCamProps.drawObject), vision.ShapeInserter);
            
            
            %en caso de quere usar los callbacks de froma asincrona se
            %pueden usar de esta forma
            %pata poder pasar this.vidR como parametro adicional (adicional
            %a this.vidL y event) a CameraLTriggerEventCallback hay que
            %usar esta notacion de cell array ver Creating Callback
            %Functions
            %this.vidL.TriggerFcn={'HWCameras.TriggerEventCallback'};
            %this.vidL.FramesAcquiredFcn={'HWCameras.CameraLFramesAcquiredEventCallback'};
            
            %DEBUG AQ para depuracion dejar comentado en general
            %aqui llamamos a imaqcallback (ver ayuda) cada trigger
            %set(this.vid,'TriggerFcn',@imaqcallback)
            
            %DEBUG AQ descomentar para que salga la info de captura de vidR
            % set(this.vidR,'FramesAcquiredFcn',@imaqcallback)
            % si quisieramos recuperar algo de info desde dentro de la
            % callback o la sacamos a traves de la funcion getdata(vid)
            % o pasamos una variable en UserData del vid
            % si lo que queremos es pasar parametros sin mas se puede
            % hacer mediante la notacion
            % this.vidL.FramesAcquiredFcn={'funName',par1,par2,...};
            
            %aqui llamamos a
            %'imaqCam.CameraLFramesAcquiredEventCallback' para cada
            %frame capturado
            %this.vid.FramesAcquiredFcn={'imaqCam.FrameAcquiredEventCallback'};
        end
    end
    
    
    %% metodos estaticos
    methods(Static)
        function save(camObj,fileName)
            % save saves camObj (an imaqCam instance) to fileName
            import OM4MClassLib.Util.*
            callFunc=Logging.WhoCalledMe();
            camClassName='imaqCam';
            
            if not(isa(camObj, camClassName))
                nameCamObj = inputname(1);
                retMsg=[nameCamObj ' must be a ' camClassName ' object'];
                error([callFunc, '->' retMsg]);
            end
            
            save(fileName,'camObj');
        end
        
        function camObj=load(fileName)
            % load loads and returns the imaqCam instance saved by save()
            % into fileName, erroring if fileName does not contain one
            import OM4MClassLib.Util.*
            callFunc=Logging.WhoCalledMe();
            camClassName='imaqCam';
            
            S=load(fileName);
            camObj=S.camObj;
            
            if not(isa(camObj, camClassName))
                retMsg=[fileName ' does not contain a ' camClassName ' object'];
                error([callFunc, '->' retMsg]);
            end
        end
        
        
        function VoidUpdatePreviewCallback(obj,event,hImage)
            % VoidUpdatePreviewCallback is a no-op preview callback that
            % just copies each acquired frame into hImage's CData; used
            % to clear a previously set UpdatePreviewWindowFcn
            set(hImage, 'CData', event.Data);
        end

        function toYCBCRCallback(obj,event,hImage)
            % toYCBCRCallback is a preview callback that converts each
            % acquired RGB frame to YCbCr before drawing it in hImage
            % get current image frame.
            I=event.Data; %esto es lo correcto pero tb se puede usar I=getsnapshot(obj);
                                   
            set(hImage, 'CData', rgb2ycbcr(I));
        end
        
        function insertLensMarks(obj,event,hImage, lensMarks)
            % insertLensMarks is a preview callback that overlays
            % crosshair lines and two lens-position marker circles
            % (lensMarks.pos, in mm, converted via lensMarks.imageSizeX)
            % used by the transmission deflectometer setup
            % get current image frame.
            I=event.Data; %esto es lo correcto pero tb se puede usar I=getsnapshot(obj);
                                  
            % get image size
            [NR, NC, NP]=size(I);
            xm=round(0.5*NC);
            ym=round(0.5*NR);
            lineH=[1, ym, NC, ym];
            lineV=[xm, 1, xm, NR];
            allLines=[lineH; lineV];
            
            %Computer Vision ToolBox insert lines
            I = insertShape(I, 'line', allLines,'LineWidth',5);
            
            %insert marks at 32 mm
            mm2px=NC/lensMarks.imageSizeX;%mm            
            xc=lensMarks.pos;%mm
            circleL=[ xm-xc*mm2px, ym, 20 ];
            circleR=[ xm+xc*mm2px, ym, 20 ];
            allCircles=[circleL; circleR];
            I = insertShape(I, 'circle', allCircles,'LineWidth',5);
            
            
                                   
            set(hImage, 'CData', I);
        end

        
        function detectEdgeCallback(obj,event,hImage)
            % detectEdgeCallback is a preview callback that replaces each
            % acquired frame with its edge map (via edge(), on the
            % grayscale conversion if the frame is RGB)
            % get current image frame.
            I=event.Data; %esto es lo correcto pero tb se puede usar I=getsnapshot(obj);
            
            [~, ~, NP]=size(I);
            if NP==3
                g=edge(rgb2gray(I));
            else
                g=edge(I);
            end
            
            set(hImage, 'CData', cat(3, g, g, g));
            
        end
        
        function subtractRefImageCallback(obj,event,hImage, refImage)
            % subtractRefImageCallback is a preview callback that
            % displays each acquired frame minus refImage (same type as
            % event.Data)
            % obj � The video input object being previewed
            % event � An event structure containing image frame information. For more information, see below.
            % himage � A handle to the image object that is being updated
            % refImage referencia image to subtract for every input image
            % in event. It must be same type that event.Data
            % to pass this function handle use
            % refImage=ones(10); %a example value
            %then define a functon handle of three params
            %[obj,event,hImage] and pass refImage as a fixed param
            % f=@(obj,event,hImage)imaqCam.subtractRefImageCallback(obj,event,hImage, refImage)
            
            % get current image frame.
            I=event.Data; %esto es lo correcto pero tb se puede usar I=getsnapshot(obj);
            dI=imsubtract(I, refImage);
           
            set(hImage, 'CData', dI);
            
        end
        
        
        function detectCornerPointsCallback(obj,event,hImage)
            % detectCornerPointsCallback is a preview callback that
            % detects corner points (via corner(), using
            % camProps.detectCornerParams from hImage's appdata) and
            % overlays them as circles on each acquired frame
            % this is useful for preview purpouses
            % obj � The video input object being previewed
            % event � An event structure containing image frame information. For more information, see below.
            % himage � A handle to the image object that is being updated
            
            % this callback is based in the update_livehistogram_display.m callback
            % example
            
            % get current image frame.
            I=event.Data; %esto es lo correcto pero tb se puede usar I=getsnapshot(obj);
            [NR, NC, NP]=size(I);
            
            %transform to uint8 GV
            if(NP==3)
                g=uint8(rgb2gray(I));
            else
                g=I;
            end
            
            %detect corners
            %aqui mostramos como recuperar los parametros que se han
            %pasado previamente en la funcion SetUpdatePreviewWindowFcnCamera
            camProps=getappdata(hImage, 'camProps');
            detectCornerParams=camProps.Get(char(imaqCamProps.detectCornerParams));
            C = corner(g,...
                'QualityLevel', detectCornerParams.QualityLevel, ...
                'method', detectCornerParams.Method,...
                'SensitivityFactor', detectCornerParams.SensitivityFactor);
            
            
            r=int32(C(:,1))';  c=int32(C(:,2))';
            if(isempty(r)||isempty(r))
                r=int32(1);
                c=int32(1);
            end
            nC=length(r);
            
            %circle radius R=4 px
            R=4*ones(1, nC, 'int32');
            circles2draw=[r;c;R]'; %Mx3
            
            %draw circles on image
            %if we don clone at the end we must release
            %shapes = clone(detectCornerParams.drawObject);
            shapes = clone(camProps.Get(char(imaqCamProps.drawObject)));
            shapes.Shape = 'Circles';
            %ver http://www.mathworks.com/help/toolbox/vision/ref/vision.shapeinserterclass.html
            %tb se podria hacer con un objeto MarkerInserter
            shapes.BorderColor = 'custom';
            shapes.CustomBorderColor=[255*ones(nC, 1), zeros(nC, 1), zeros(nC, 1)];
            
            
            %to draw in color input image must be RGB
            I=step(shapes, I, circles2draw);
            %g=step(shapes, cat(3, g, g, g), circles2draw);
            %release(shapes); if we do not clone we must release
            
            sizeCData=getappdata(hImage, 'sizeCData');
            if(length(sizeCData)==2) %solo hay dos dimensiones
                set(hImage, 'CData', rgb2gray(I));
            else
                set(hImage, 'CData', I);
            end
            %drawnow; % Refresh the display. this is necesary in the
            %update_livehistogram_display.m, however here it generates a 'UpdatePreviewWindowFcn' event that makes a
            %second call to detectCornerPointsCallback with the data
            %already modified by the shapes object
        end
        
        
        function TriggerEventCallback(vid, event)
            % TriggerEventCallback is a TriggerFcn callback fired right
            % after trigger(vid); currently a no-op placeholder

        end

        function FrameAcquiredEventCallback(vid, event)
            % FrameAcquiredEventCallback is a FramesAcquiredFcn callback
            % that forwards to imaqcallback (prints capture timing)
            %DEBUG AQ descomentar para que salga el tiempo de captura en
            %pantalla
            imaqcallback(vid, event);
        end
        
        function StopAllCameras()
            % StopAllCameras stops, deletes and clears every videoinput
            % object currently found by imaqfind
            vids=imaqfind;
            
            for n=1:length(vids)
                stop(vids(n));
                delete(vids(n));
                clear vids(n);
            end
        end
        
        function [vidwv, devicewv]=getFirstImaqCamAvailable()
            % getFirstImaqCamAvailable returns a videoinput/source pair
            % for the first 'winvideo' device, or [] with a warning
            % dialog if no Image Acquisition adaptors are installed
            import OM4MClassLib.Util.*
            callFunc=Logging.WhoCalledMe();
            
            imaqInfo = imaqhwinfo;
            if isempty(imaqInfo.InstalledAdaptors)
                vidwv=[];
                devicewv=[];
                retMsg=['No Image Acquisition adaptors found (check with imaqtool)' ];
                warndlg([callFunc, '->' retMsg]);
            else
            
            vidwv=videoinput('winvideo', 1);
            devicewv = getselectedsource(vidwv);
            end
        end
        
        function vid=getVidFromName(adaptorName, name, vidFormat)
            % getVidFromName returns a videoinput for the device named
            % name under adaptorName (e.g. 'winvideo'), using vidFormat
            % (e.g. 'MJPG_160x120'); errors if name is not found
            %             adaptorName='winvideo';
            %             name='HD WebCam';
            %             vidFormat = 'MJPG_160x120';
            
            import OM4MClassLib.Util.*;
            callFunc=Logging.WhoCalledMe();
            
            info = imaqhwinfo(adaptorName);
            deviceIDList=info.DeviceIDs; %cell array of IDs
            N=length(deviceIDList);
            namesList=cell(1, N);
            for n=1:N
                dev_info = imaqhwinfo(adaptorName, deviceIDList{n});
                namesList{n}=dev_info.DeviceName;
            end
            
            index = find(ismember(namesList, name));
            if isempty(index)
                retMsg=[callFunc ' : error loading Adaptor ' adaptorName ' for Camera ' name ' with Format ' vidFormat];
                error(retMsg);
            end
            deviceID=deviceIDList{index};
            
            vid=videoinput(adaptorName, deviceID, vidFormat);
            
            %if desired some general props can be set for example
            
            %src = getselectedsource(vid);
            %             vid.FramesPerTrigger = 1;
            %             vid.ReturnedColorspace = 'grayscale';
            %
            %             if isprop(src, 'ExposureMode')
            %                 src.ExposureMode = 'manual';
            %             end
            %
            %             if isprop(src, 'GainMode')
            %                 src.GainMode = 'manual';
            %             end
            %
            %             if isprop(src, 'BacklightCompensation')
            %                 src.BacklightCompensation = 'off';
            %             end
            %
            %             if isprop(src, 'WhiteBalanceMode')
            %                 src.ExposureMode = 'manual';
            %             end
            
        end
        
        
        
        function CDS = GenCamDataStruct()
            % GenCamDataStruct builds an empty struct with one field per
            % EnumImaqCamData member, each initialized to []
            %  Known gap: EnumImaqCamData does not exist anywhere in this
            % repo, so this method cannot currently run
            [~, CDSFields]=enumeration('EnumImaqCamData');
            vals=cell(size(CDSFields)); %empty cell array
            CDS=cell2struct(vals, CDSFields);
            
            %set def values for all fields
            for n=1:length(CDSFields)
                CDS.(CDSFields{n})=[];
            end
            
        end
        
        function r=isCamDataStruct(CDS)
            % isCamDataStruct returns true if CDS's field names match
            % EnumImaqCamData exactly (see GenCamDataStruct's known gap:
            % EnumImaqCamData does not exist in this repo)

            f1=fieldnames(CDS); %CDS field names
            [~, f2]=enumeration('EnumImaqCamData');  %enumeration field names
            
            r=isequal(f1, f2);
        end
        
        
    end
    
    %% get set nethods
    methods
        function value = get.Data(this)
            % get.Data returns this.Data (the last captured imaqCamData)
            value=this.Data;
        end
    end


    %% public IProps interface
    methods
        function ret=Get(this, props)
            % Get returns this.props.Get(props), or all props if called
            % with no props argument (IProps interface)
            if nargin==1
                ret=this.props.Get();
            else
                ret=this.props.Get(props);
            end
        end
        
        function this=Set(this, props, propvals)
            % Set sets this.props.(props)=propvals (IProps interface);
            % for props=='geomCalFile' also loads propvals into this.gc
            % via camGeomCal.loadCal (this.gc does not exist in this
            % repo, see the class-level known-gap note)
            switch props
                case 'geomCalFile'
                    this.gc.loadCal(propvals);
            end
            
            this.props.Set(props, propvals);
        end
    end
end
